# Generated by Django 4.1.2 on 2023-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_amenities_hotel_hotelbooking_hotelimages_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelimages",
            name="images",
            field=models.ImageField(upload_to="hotels"),
        ),
    ]
