# Generated by Django 4.1.2 on 2023-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_hotelimages_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelbooking",
            name="booked_on",
            field=models.DateField(auto_now=True),
        ),
    ]
