# Generated by Django 4.1.2 on 2023-01-10 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_hotelbooking_booked_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("package_name", models.CharField(max_length=50)),
                ("Package_description", models.CharField(max_length=200)),
                ("package_images", models.ImageField(upload_to="package")),
                ("package_price", models.IntegerField()),
                ("package_amenity_name", models.CharField(max_length=100)),
                ("package_days", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
