# Generated by Django 4.1.2 on 2023-01-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_package_package_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="package_amenity_name",
        ),
        migrations.RemoveField(
            model_name="package",
            name="package_days",
        ),
        migrations.RemoveField(
            model_name="package",
            name="package_price",
        ),
    ]
